#!/usr/bin/env python
import sys
from sys import argv
import argparse

citation = 'Please cite our paper'
parser = argparse.ArgumentParser(epilog = citation)
parser.add_argument('-r', metavar='reference.vcf', help='reference vcf file path')
