#!/usr/bin/env python
import sys
from sys import argv
import argparse

citation = 'Please cite our paper'
parser = argparse.ArgumentParser(epilog = citation)
parser.add_argument('-s', metavar='simple.vcf', help='direct match vcf result')
parser.add_argument('-c', metavar='complex.vcf', help='clustering match vcf result')

if(args.s is not None):
    print('Analysis direct match vcf results')
    with open(args.s) as simple_vcf:
        for line in simple_vcf.readlines():
            if line.startswith('#'):
                continue
            columns = line.split('\t')
            ref = 

